name: GSC to Airtable Automation

on:
  schedule:
    - cron: "0 8 1 * *" # Runs at 8 AM UTC on the 1st of every month
  workflow_dispatch: # Allows manual trigger

jobs:
  gsc-to-airtable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run GSC to Airtable script
      run: |
        python gsc_to_airtable.py
